# config file SSVM build tool
# 10-1-24 Mike Kuriger

# configs used for adding VM to DNS in EIP

eip:
    master: "st1dceipmaster.corp.pvt"
    credentials:
        username: "mk7193"
        password: "Mrkamk2021#"
    
    datacenters:
        st1:
            name: "DFW Data Center"                # this is the name of the DC container in EIP
            networks:                               
                VLAN540: "ST1 - Weblogic"          
                VLAN673: "vlan673_vmware_management"
                VLAN421: "vlan 421- linux_421"
        ev3:
            name: "Ashburn Datacenter"
            networks:
                VLAN540: "EV3 - Weblogic"
                VLAN673: "vlan673_vmware_management"
                VLAN421: "vlan 421- linux_421"

# add_vm_to_dns.py --dc $DC --network $VLAN --hostname ${VM}.corp.pvt --mac $MAC

# govc vm.clone -on=false -vm $OS -c $CPU -m $MEM -net $NET -pool /st1dccomp01/host/${CL}/Resources -datastore-cluster ${DSC} -folder '/st1dccomp01/vm/vRA - Thryv Cloud/TESTING' $VM
# govc vm.customize -vm $VM -type Linux -name $VM -domain corp.pvt --mac $MAC -ip $IP -netmask $NM -gateway $GW -dns-server $DNS -dns-suffix "$DOMAINS"


# configs used for building VM in Vcenter

datacenters:
    st1:
        vcenter: "st1vccomp01a.corp.pvt"
        credentials:
            username: "administrator@vsphere.local"
            password: "X5r%QZ6VCp4BsEG3He2w"
        # vlans:
        #     VLAN540: 
        #         label: "ST1 - VLAN540"          # name displayed in ssvm
        #         net:  "10.5.32-VLAN540-DvS"     # network in vcenter, used for VMbuild for attaching the nic card to the vlan
        #         netmask: "255.255.252.0"        # netmask, used when customizing VMbuild with IP address info
        #     VLAN421: 
        #         desc: "ST1 - VLAN421"
        #         net:  "10.2.4-VLAN421-DvS"
        #         netmask: "255.255.252.0"
        clusters:                               
              - B-2-1
              - B-2-2
              - B-2-3
              - B-2-4
              - B-2-6
              - B-2-7
              - B-2-8
              - B-2-9
        # DNS:
        #     - 10.6.1.111
        #     - 10.4.1.111

    ev3:
        name: "Ashburn Datacenter"
        vcenter: "ev3vccomp01a.corp.pvt"
        credentials:
            username: "administrator@vsphere.local"
            password: "kLo5(S&iYQSH"
        # vlans:
        #     VLAN540:
        #         desc: "EV3 - Weblogic"
        #         net: "10.2.32-VLAN540-DvS"
        #         netmask: "255.255.252.0"
        #     VLAN673:
        #         desc: "vlan673_vmware_management"
        #         net: "10.2.106-VLAN673-DvS"
        #         netmask: "255.255.254.0"
        #     VLAN421:
        #         desc: "vlan 421- linux_421"
        #         net: "10.2.4-VLAN421-DvS"
        #         netmask: "255.255.252.0"
        # clusters:
        #     - A-1-1
        #     - A-1-2
        #     - A-1-3
        #     - A-1-4
        #     - A-1-5
        #     - A-1-6
        #     - A-1-7
        #     - A-1-8
        # DNS:
        #     - 10.4.1.111
        #     - 10.6.1.111

server_types:
    lnp: 'Production'
    lnd: 'Development'
    lnw: 'Testing'
    lnq: 'QA'

oss:
    SSVM-OEL7: 'Oracle Enterprise Linux 7'
    SSVM-OEL8: 'Oracle Enterprise Linux 8'
    SSVM-OEL9: 'Oracle Enterprise Linux 9'
    
    
centrify_zones:
    grp-dba:
    grp-sre:
    grp-unix:
    grp-vra:
    app-ceph:
